# BUILD redisfab/arm32v7-xbuild:buster

FROM multiarch/qemu-user-static:x86_64-arm-4.1.0-1 as qemu

FROM debian:buster-slim

COPY bin/ /usr/bin/
COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin/

RUN rm -f /usr/bin/qemu-aarch64-static
RUN chown root:root /usr/bin/qemu-*-static ;\
	chmod 755 /usr/bin/qemu-*-static
