# BUILD redisfab/arm32v7-xbuild:stretch

FROM debian:stretch-slim

COPY bin/ /usr/bin/
RUN rm -f /usr/bin/qemu-aarch64-static
RUN chown root:root /usr/bin/qemu-*-static ;\
	chmod 755 /usr/bin/qemu-*-static
